services:
  - type: web
    name: auctionhub-demo
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && (python manage.py loaddata initial_data || true) && gunicorn auction_project.wsgi --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
