# Generated by Django 5.2.15 on 2026-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_listing_active_ends_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='listing_thumbnails/'),
        ),
    ]
