# Generated by Django 6.0.5 on 2026-07-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dailyvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_document',
            field=models.FileField(blank=True, upload_to='id_documents/'),
        ),
    ]
