# Generated by Django 6.0.5 on 2026-07-21 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_is_winner'),
        ('listings', '0004_listing_listing_active_ends_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount', 'created_at']},
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['listing', '-amount', 'created_at'], name='bid_listing_amount_idx'),
        ),
    ]
