# Generated by Django 5.2.15 on 2026-07-22 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_bid_options_bid_bid_listing_amount_idx'),
        ('listings', '0004_listing_listing_active_ends_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bids', to='listings.listing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('listing', 'bidder'), name='one_autobid_per_bidder_per_listing')],
            },
        ),
    ]
