# Generated by Django 5.2.15 on 2026-07-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bid_is_auto_autobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobid',
            name='increment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
