# Generated by Django 5.2.15 on 2026-07-22 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('outbid', 'You have been outbid'), ('auction_won', 'You won an auction'), ('auction_lost', 'You lost an auction'), ('auction_ending', 'Auction ending soon'), ('auction_sold', 'Your item was sold'), ('new_bid', 'New bid on your listing'), ('new_message', 'New message'), ('auto_bid_placed', 'Auto-bid placed on your behalf'), ('auto_bid_exceeded', 'Your auto-bid limit was exceeded')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notif_user_created_idx'), models.Index(fields=['user', 'is_read'], name='notif_user_read_idx')],
            },
        ),
    ]
